[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.16"
aws-sdk-codebuild = "1.75.0"
aws-sdk-dynamodb = "1.65.0"
rust-analyzer = "0.0.1"
tokio = { version = "1", features = ["full"] }
