---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
version: 0.2
phases:
  install:
    commands:
      - echo "Installing Rust ..."
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
      - echo "Installing cmake ..."
      - apt-get update -y
      - apt-get install -y cmake
  pre_build:
    commands:
      - |
        cd bindings/rust/extended
        ./generate.sh
        cargo clean
  build:
    commands:
      - cargo build --timings
  post_build:
    commands:
      - cargo test --timings

artifacts:
  # upload timing reports
  files:
    - '**/*'
  base-directory: ./bindings/rust/extended/target/cargo-timings/*.html
